# Generated by Django 2.0.4 on 2018-04-21 12:23

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', smartfields.fields.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\github\\client\\src\\assets\\image'), upload_to='%Y/%m/%d/orig')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created', '-pk'),
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='path',
        ),
        migrations.AddField(
            model_name='images',
            name='photoId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='imageRelate', to='photo.Photo'),
        ),
    ]
