# Generated by Django 2.0.4 on 2018-07-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180722_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photoId',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='imageRelate', to='photo.Photo'),
        ),
    ]
